language: c
dist: bionic
before-install:
  - sudo apt-get update
  - sudo apt-get install python3-pip -y
  - sudo apt-get install doxygen -y
  - sudo apt-get install gcc -y
  - sudo pip3 install gcovr
  - sudo apt-get install ruby-full
  - gem install rubygems-update
  - update_rubygems
  - sudo gem install ceedling
script: make && make run && make test
