language: c

before-install:
  - sudo apt-get update
  - sudo apt-get install python3-pip -y
  - sudo apt-get install doxygen -y
  - sudo apt-get install gcc -y
  - sudo pip3 install gcovr
  - sudo gem install ceedling
  - gem install rubygems-update
  - update_rubygems

script: make && make run && make test
rvm:
  - 2.5.3
